const deckOfCards = [
  {
    imgPath: './Images/cards/A-Spades.png',
    name: 'A',
    suit: '♠️',
    value: 11,
  },
  {
    imgPath: './Images/cards/A-Diamonds.png',
    name: 'A',
    suit: '♦️',
    value: 11,
  },
  {
    imgPath: './Images/cards/A-Clubs.png',
    name: 'A',
    suit: '♣️',
    value: 11,
  },
  {
    imgPath: './Images/cards/A-Hearts.png',
    name: 'A',
    suit: '♥️',
    value: 11,
  },
  {
    imgPath: './Images/cards/2-Spades.png',
    name: '2',
    suit: '♠',
    value: 2,
  },
  {
    imgPath: './Images/cards/2-Diamonds.png',
    name: '2',
    suit: '♦️',
    value: 2,
  },
  {
    imgPath: './Images/cards/2-Clubs.png',
    name: '2',
    suit: '♣',
    value: 2,
  },
  {
    imgPath: './Images/cards/2-Hearts.png',
    name: '2',
    suit: '♥️',
    value: 2,
  },
  {
    imgPath: './Images/cards/3-Spades.png',
    name: '3',
    suit: '♠',
    value: 3,
  },
  {
    imgPath: './Images/cards/3-Diamonds.png',
    name: '3',
    suit: '♦',
    value: 3,
  },
  {
    imgPath: './Images/cards/3-Clubs.png',
    name: '3',
    suit: '♣',
    value: 3,
  },
  {
    imgPath: './Images/cards/3-Hearts.png',
    name: '3',
    suit: '♥',
    value: 3,
  },
  {
    imgPath: './Images/cards/4-Spades.png',
    name: '4',
    suit: '♠',
    value: 4,
  },
  {
    imgPath: './Images/cards/4-Diamonds.png',
    name: '4',
    suit: '♦',
    value: 4,
  },
  {
    imgPath: './Images/cards/4-Clubs.png',
    name: '4',
    suit: '♣',
    value: 4,
  },
  {
    imgPath: './Images/cards/4-Hearts.png',
    name: '4',
    suit: '♥',
    value: 4,
  },
  {
    imgPath: './Images/cards/5-Spades.png',
    name: '5',
    suit: '♠',
    value: 5,
  },
  {
    imgPath: './Images/cards/5-Diamonds.png',
    name: '5',
    suit: '♦',
    value: 5,
  },
  {
    imgPath: './Images/cards/5-Clubs.png',
    name: '5',
    suit: '♣',
    value: 5,
  },
  {
    imgPath: './Images/cards/5-Hearts.png',
    name: '5',
    suit: '♥',
    value: 5,
  },
  {
    imgPath: './Images/cards/6-Spades.png',
    name: '6',
    suit: '♠',
    value: 6,
  },
  {
    imgPath: './Images/cards/6-Diamonds.png',
    name: '6',
    suit: '♦',
    value: 6,
  },
  {
    imgPath: './Images/cards/6-Clubs.png',
    name: '6',
    suit: '♣',
    value: 6,
  },
  {
    imgPath: './Images/cards/6-Hearts.png',
    name: '6',
    suit: '♥',
    value: 6,
  },
  {
    imgPath: './Images/cards/7-Spades.png',
    name: '7',
    suit: '♠',
    value: 7,
  },
  {
    imgPath: './Images/cards/7-Diamonds.png',
    name: '7',
    suit: '♦',
    value: 7,
  },
  {
    imgPath: './Images/cards/7-Clubs.png',
    name: '7',
    suit: '♣',
    value: 7,
  },
  {
    imgPath: './Images/cards/7-Hearts.png',
    name: '7',
    suit: '♥',
    value: 7,
  },
  {
    imgPath: './Images/cards/8-Spades.png',
    name: '8',
    suit: '♠',
    value: 8,
  },
  {
    imgPath: './Images/cards/8-Diamonds.png',
    name: '8',
    suit: '♦',
    value: 8,
  },
  {
    imgPath: './Images/cards/8-Clubs.png',
    name: '8',
    suit: '♣',
    value: 8,
  },
  {
    imgPath: './Images/cards/8-Hearts.png',
    name: '8',
    suit: '♥',
    value: 8,
  },
  {
    imgPath: './Images/cards/9-Spades.png',
    name: '9',
    suit: '♠',
    value: 9,
  },
  {
    imgPath: './Images/cards/9-Diamonds.png',
    name: '9',
    suit: '♦',
    value: 9,
  },
  {
    imgPath: './Images/cards/9-Clubs.png',
    name: '9',
    suit: '♣',
    value: 9,
  },
  {
    imgPath: './Images/cards/9-Hearts.png',
    name: '9',
    suit: '♥',
    value: 9,
  },
  {
    imgPath: './Images/cards/10-Spades.png',
    name: '10',
    suit: '♠',
    value: 10,
  },
  {
    imgPath: './Images/cards/10-Diamonds.png',
    name: '10',
    suit: '♦',
    value: 10,
  },
  {
    imgPath: './Images/cards/10-Clubs.png',
    name: '10',
    suit: '♣',
    value: 10,
  },
  {
    imgPath: './Images/cards/10-Hearts.png',
    name: '10',
    suit: '♥',
    value: 10,
  },
  {
    imgPath: './Images/cards/J-Spades.png',
    name: 'J',
    suit: '♠',
    value: 10,
  },
  {
    imgPath: './Images/cards/J-Diamonds.png',
    name: 'J',
    suit: '♦',
    value: 10,
  },
  {
    imgPath: './Images/cards/J-Clubs.png',
    name: 'J',
    suit: '♣',
    value: 10,
  },
  {
    imgPath: './Images/cards/J-Hearts.png',
    name: 'J',
    suit: '♥',
    value: 10,
  },
  {
    imgPath: './Images/cards/Q-Spades.png',
    name: 'Q',
    suit: '♠',
    value: 10,
  },
  {
    imgPath: './Images/cards/Q-Diamond.png',
    name: 'Q',
    suit: '♦',
    value: 10,
  },
  {
    imgPath: './Images/cards/Q-Clubs.png',
    name: 'Q',
    suit: '♣',
    value: 10,
  },
  {
    imgPath: './Images/cards/Q-Hearts.png',
    name: 'Q',
    suit: '♥',
    value: 10,
  },
  {
    imgPath: './Images/cards/K-Spades.png',
    name: 'K',
    suit: '♠',
    value: 10,
  },
  {
    imgPath: './Images/cards/K-Diamonds.png',
    name: 'K',
    suit: '♦',
    value: 10,
  },
  {
    imgPath: './Images/cards/K-Clubs.png',
    name: 'K',
    suit: '♣',
    value: 10,
  },
  {
    imgPath: './Images/cards/K-Hearts.png',
    name: 'K',
    suit: '♥',
    value: 10,
  },
];

export default deckOfCards;
